# Creating LIB table
## Marissa Burton

### Load in packages

In [10]:
from glob import glob
import pandas as pd

In [28]:
CORPUS = pd.read_csv('data/CORPUS.csv')

/var/folders/k2/xkhh4x_x2999dprlhrz1h_r00000gn/T/ipykernel_94135/1873822874.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  CORPUS = pd.read_csv('data/CORPUS.csv')

### Load in file paths

In [12]:
source_file_list = sorted(glob('data/source_file_dir/*'))

### Create book data

In [14]:
book_data = []
for source_file_path in source_file_list:
    book_id = int(source_file_path.split('-')[-1].split('.')[0].replace('pg',''))
    raw_title = source_file_path.split('/')[-1].split('-')[0].replace('_', ' ')
    book_data.append((book_id, source_file_path, raw_title))

# Show example
book_data[0]

(1952,
 'data/source_file_dir/GILMAN_CHARLOTTE_PERKINS_THE_YELLOW_WALLPAPER-pg1952.txt',
 'GILMAN CHARLOTTE PERKINS THE YELLOW WALLPAPER')

### Create LIB table

In [ ]:
LIB = pd.DataFrame(book_data, columns=['book_id','source_file_path', 'raw_title'])\
    .set_index('book_id').sort_index()

,source_file_path,raw_title
book_id,,
43,data/source_file_dir/STEVENSON_ROBERT_LOUIS_TH...,STEVENSON ROBERT LOUIS THE STRANGE CASE OF DR ...
175,data/source_file_dir/LEROUX_GASTON_THE_PHANTOM...,LEROUX GASTON THE PHANTOM OF THE OPERA
345,data/source_file_dir/STOKER_BRAM_DRACULA-pg345...,STOKER BRAM DRACULA
696,data/source_file_dir/WALPOLE_HORACE_THE_CASTLE...,WALPOLE HORACE THE CASTLE OF OTRANTO
1952,data/source_file_dir/GILMAN_CHARLOTTE_PERKINS_...,GILMAN CHARLOTTE PERKINS THE YELLOW WALLPAPER
3268,data/source_file_dir/RADCLIFFE_ANN_WARD_THE_MY...,RADCLIFFE ANN WARD THE MYSTERIES OF UDOLPHO
5182,data/source_file_dir/REEVE_CLARA_THE_OLD_ENGLI...,REEVE CLARA THE OLD ENGLISH BARON A GOTHIC STORY
6087,data/source_file_dir/POLIDORI_JOHN_WILLIAM_THE...,POLIDORI JOHN WILLIAM THE VAMPYRE
12122,data/source_file_dir/JACOBS_W_W_THE_MONKEY'S_P...,JACOBS W W THE MONKEY'S PAW
41445,data/source_file_dir/SHELLEY_MARY_WOLLSTONECRA...,SHELLEY MARY WOLLSTONECRAFT FRANKENSTEIN
53685,data/source_file_dir/MATURIN_CHARLES_ROBERT_ME...,MATURIN CHARLES ROBERT MELMOTH THE WANDERER VO...
20180856,data/source_file_dir/JACKSON_SHIRLEY_THE_HAUNT...,JACKSON SHIRLEY THE HAUNTING OF HILL HOUSE

#### Fix author and title values for LIB table

In [26]:
try:
    LIB['author'] = LIB.raw_title.apply(lambda x: ', '.join(x.split()[:2]))
    LIB['title'] = LIB.raw_title.apply(lambda x: ' '.join(x.split()[2:]))
    LIB = LIB.drop('raw_title', axis=1)

# Skip if this cell has already been run
except AttributeError:
    pass

LIB.loc[43, 'author'] = 'STEVENSON, ROBERT LOUIS'
LIB.loc[1952, 'author'] = 'GILMAN, CHARLOTTE PERKINS'
LIB.loc[3268, 'author'] = 'RADCLIFFE, ANN WARD'
LIB.loc[6087, 'author'] = 'POLIDORI, JOHN WILLIAM'
LIB.loc[12122, 'author'] = 'JACOBS, W.W.'
LIB.loc[41445, 'author'] = 'SHELLEY, MARY WOLLSTONECRAFT'

LIB.loc[43, 'title'] = 'THE STRANGE CASE OF DR JEKYLL AND MR HYDE'
LIB.loc[1952, 'title'] = 'THE YELLOW WALLPAPER'
LIB.loc[3268, 'title'] = 'THE MYSTERIES OF UDOLPHO'
LIB.loc[6087, 'title'] = 'THE VAMPYRE'
LIB.loc[12122, 'title'] = "THE MONKEY'S PAW"
LIB.loc[41445, 'title'] = 'FRANKENSTEIN'

#### Add book length

In [ ]:
LIB['book_len'] = CORPUS.groupby('book_id').term_str.count()

,source_file_path,author,title,book_len
book_id,,,,
12122,data/source_file_dir/JACOBS_W_W_THE_MONKEY'S_P...,"JACOBS, W.W.",THE MONKEY'S PAW,4023
1952,data/source_file_dir/GILMAN_CHARLOTTE_PERKINS_...,"GILMAN, CHARLOTTE PERKINS",THE YELLOW WALLPAPER,6193
6087,data/source_file_dir/POLIDORI_JOHN_WILLIAM_THE...,"POLIDORI, JOHN WILLIAM",THE VAMPYRE,11065
43,data/source_file_dir/STEVENSON_ROBERT_LOUIS_TH...,"STEVENSON, ROBERT LOUIS",THE STRANGE CASE OF DR JEKYLL AND MR HYDE,25798
696,data/source_file_dir/WALPOLE_HORACE_THE_CASTLE...,"WALPOLE, HORACE",THE CASTLE OF OTRANTO,34654
5182,data/source_file_dir/REEVE_CLARA_THE_OLD_ENGLI...,"REEVE, CLARA",THE OLD ENGLISH BARON A GOTHIC STORY,55191
53685,data/source_file_dir/MATURIN_CHARLES_ROBERT_ME...,"MATURIN, CHARLES",ROBERT MELMOTH THE WANDERER VOL. 1,56938
20180856,data/source_file_dir/JACKSON_SHIRLEY_THE_HAUNT...,"JACKSON, SHIRLEY",THE HAUNTING OF HILL HOUSE,65454
41445,data/source_file_dir/SHELLEY_MARY_WOLLSTONECRA...,"SHELLEY, MARY WOLLSTONECRAFT",FRANKENSTEIN,67204
3268,data/source_file_dir/RADCLIFFE_ANN_WARD_THE_MY...,"RADCLIFFE, ANN WARD",THE MYSTERIES OF UDOLPHO,70534
175,data/source_file_dir/LEROUX_GASTON_THE_PHANTOM...,"LEROUX, GASTON",THE PHANTOM OF THE OPERA,83686
345,data/source_file_dir/STOKER_BRAM_DRACULA-pg345...,"STOKER, BRAM",DRACULA,162932

#### Add number of chapters

In [ ]:
LIB['n_chaps'] = CORPUS.reset_index()[['book_id','chap_num']]\
    .drop_duplicates()\
    .groupby('book_id').chap_num.count()

,source_file_path,author,title,book_len,n_chaps
book_id,,,,,
43,data/source_file_dir/STEVENSON_ROBERT_LOUIS_TH...,"STEVENSON, ROBERT LOUIS",THE STRANGE CASE OF DR JEKYLL AND MR HYDE,25798,9
175,data/source_file_dir/LEROUX_GASTON_THE_PHANTOM...,"LEROUX, GASTON",THE PHANTOM OF THE OPERA,83686,26
345,data/source_file_dir/STOKER_BRAM_DRACULA-pg345...,"STOKER, BRAM",DRACULA,162932,27
696,data/source_file_dir/WALPOLE_HORACE_THE_CASTLE...,"WALPOLE, HORACE",THE CASTLE OF OTRANTO,34654,5
1952,data/source_file_dir/GILMAN_CHARLOTTE_PERKINS_...,"GILMAN, CHARLOTTE PERKINS",THE YELLOW WALLPAPER,6193,1
3268,data/source_file_dir/RADCLIFFE_ANN_WARD_THE_MY...,"RADCLIFFE, ANN WARD",THE MYSTERIES OF UDOLPHO,70534,13
5182,data/source_file_dir/REEVE_CLARA_THE_OLD_ENGLI...,"REEVE, CLARA",THE OLD ENGLISH BARON A GOTHIC STORY,55191,1
6087,data/source_file_dir/POLIDORI_JOHN_WILLIAM_THE...,"POLIDORI, JOHN WILLIAM",THE VAMPYRE,11065,4
12122,data/source_file_dir/JACOBS_W_W_THE_MONKEY'S_P...,"JACOBS, W.W.",THE MONKEY'S PAW,4023,3
41445,data/source_file_dir/SHELLEY_MARY_WOLLSTONECRA...,"SHELLEY, MARY WOLLSTONECRAFT",FRANKENSTEIN,67204,23
53685,data/source_file_dir/MATURIN_CHARLES_ROBERT_ME...,"MATURIN, CHARLES",ROBERT MELMOTH THE WANDERER VOL. 1,56938,5
20180856,data/source_file_dir/JACKSON_SHIRLEY_THE_HAUNT...,"JACKSON, SHIRLEY",THE HAUNTING OF HILL HOUSE,65454,9

#### Add eras

In [39]:
LIB['era'] = CORPUS.groupby('book_id')['era'].first()

In [ ]:
cols = LIB.columns.tolist()

cols.insert(1, cols.pop(cols.index('era')))

LIB = LIB[cols]

#### Get average book length

In [49]:
LIB['book_len'].mean()

np.float64(53639.333333333336)

### Export LIB table

In [50]:
LIB.to_csv('data/LIB.csv')